coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

ignore:
  - "web/"
  - "**/*_test.go"
  - "cmd/"
  - "docs/"
  - "examples/"
  - "scripts/"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
